### ISSUE TITLE
Add Code for Doubly Linked List #1

### ISSUE THREAD

**Issue by aryan-harsh** [aryan-harsh/DS-Algo-Codes#1]
add code for doubly linked list implementation, that is, insertion, deletion, traversal.

**Comment by MARK-42** [comment]
I want to contribute

**Comment by aryan-harsh** [comment]
@MARK-42 assigned .

**Comment by Eunoia1729** [comment]
Sir, can i take up the issue

**Comment by aryan-harsh** [comment]
@MARK-42  @Eunoia1729  both of you can take up the issue. Add your code in Data Structures/Linked List in a file named Doubly_List_(Yourname)

**Comment by G1-10ST** [comment]
@aryan-harsh Please let me solve this Issue !

**Comment by aryan-harsh** [comment]
@Eunoia1729 @MARK-42 are you taking this issue??

@G1-10ST you can take up this issue. Assigning you.
